# Generated by Django 4.2.6 on 2023-11-02 10:25

from django.db import migrations, models
import resparser.models


class Migration(migrations.Migration):

    dependencies = [
        ('resparser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeparser',
            name='file',
            field=models.FileField(upload_to=resparser.models.upload_location),
        ),
    ]
